### ISSUE TITLE
Twitter example should verify the token 

### ISSUE THREAD

**Issue by PSG-Luna** [garyburd/go-oauth#16]
According to twitter's own documentation, the token gotten from the temporary credentials URI should be verified with the token in the callback. This is currently not the case, and the token is just taken with the assumption they are identical.

**Comment by garyburd** [comment]
Is your concern that Twitter might issue the same temporary credential to more than one user, or that another user might hijack the callback?

**Comment by PSG-Luna** [comment]
A user could theoretically try and brute force the callback, if the
algorithm twitter uses to generate tokens is not 100% pure crypto secure
random, the chance this succeeds is non trivial. The same ofcourse applies
to any other examples if those aren't checked either, I only checked the
twitter appengine example.

**Comment by garyburd** [comment]
Thank you for pointing this out. I fixed the examples in c0cafec1c740ac917698bdf435b77112abd19716.
