### ISSUE TITLE
0-legged Oauth by go-oauth

### ISSUE THREAD

**Issue by wenruij** [garyburd/go-oauth#18]
Hi,
   Just wondering is it possible to do an 0-legged Oauth by your `go-oauth`?
   saying i just get an API key / secret as the consumer key,  without any token, is it possible to get the signed url with your `go-oauth`

**Comment by garyburd** [comment]
Yes. Pass nil for credentials argument.

**Comment by wenruij** [comment]
thanks garyburd,
   Do you mean argument of `AuthorizationURL` or `RequestToken` ? 
   For `RequestToken`, i don't get a `TokenRequestURI`.
   For  `AuthorizationURL` , `temporaryCredentials.Token` in `AuthorizationURL` should panic a runtime error

**Comment by garyburd** [comment]
I was referring to the credentials argument to SetAuthorizationHeader, SignForm, Get, Post, and Put.  If the application passes nil, then the request is signed with client key and secret only.

**Comment by wenruij** [comment]
thanks a lot. garyburd.

**Comment by garyburd** [comment]
I missed that you reopened this issue.  Did you get it to work by passing nil for credentials?

**Comment by wenruij** [comment]
hi, garyburd
   I have solved my problem from your guide. The re-open is an unintentional click. sorry for that.

  Thanks again.
