### ISSUE TITLE
Twitter getting error 215 Bad Authentication data

### ISSUE THREAD

**Issue by Fyb3roptik** [garyburd/go-oauth#23]
No matter what I try to do all I get is this error message. Any thoughts as to why? I have everything installed and working correctly =(

**Comment by garyburd** [comment]
Please share an example of a program that fails.

**Comment by Fyb3roptik** [comment]
http://pastebin.com/Us7aF6y2

tempCred, err := oauthClient.RequestTemporaryCredentials(nil, callback, nil)
	log.Println("CREDS: ", err)

Is where I am getting the error

**Comment by garyburd** [comment]
Are the environment variables  OAUTH_TWITTER_KEY and OAUTH_TWITTER_SECRET set to valid values?  Print the values in your application to confirm.

What is the exact error message printed by the application?

**Comment by Fyb3roptik** [comment]
Yes the ENV variables are set and are getting passed. The error message is:

OAuth server status 400, {"errors":[{"code":215,"message":"Bad Authentication data."}]}

**Comment by Fyb3roptik** [comment]
I am attempting to call my route via postman, which then calls out to twitter. I am trying to integrate twitter for login/signup on my API

**Comment by garyburd** [comment]
Here's a program similar to your code. Try this program and let me know what happens. It works with my credentials.

    package main

    import (
        "fmt"
        "os"

        "github.com/garyburd/go-oauth/oauth"
    )

    var oauthClient = oauth.Client{
        TemporaryCredentialRequestURI: "https://api.twitter.com/oauth/request_token",
        ResourceOwnerAuthorizationURI: "https://api.twitter.com/oauth/authorize",
        TokenRequestURI:               "https://api.twitter.com/oauth/access_token",
        Credentials: oauth.Credentials{
            Token:  os.Getenv("OAUTH_TWITTER_KEY"),
            Secret: os.Getenv("OAUTH_TWITTER_SECRET"),
        },
    }

    func main() {
        callback := "http://" + "example.com" + "/twitter/callback?client_id=" + "xxxx"
        tempCred, err := oauthClient.RequestTemporaryCredentials(nil, callback, nil)
        fmt.Println(tempCred, err)
    }

**Comment by Fyb3roptik** [comment]
Same thing. Does it matter that I am developing locally in a vagrant? The vagrant has access to the outside world though as I am hitting AWS with it.

**Comment by garyburd** [comment]
Vagrant should have no impact on how the package works.  Some things you can try:

- I know you said that the credentials are set correctly, but double check by  adding `fmt.Println(oauthClient.Credentials)`  to my program and confirm that correct credentials are printed.
- Run the program outside of vagrant.
